name: Dispatch to parent
on: [push]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: cattle0horse/nushell
          event-type: submodule_updated
          client-payload: '{"module":"my-submodule","sha":"${{ github.sha }}"}'
