name: Dispatch Parent Update
on:
  push:
    branches:
      - main
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch update to dotfiles repository
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: Cattle0Horse/dotfiles
          event-type: update-submodule
